// <auto-generated />
using System;
using INNOBRA_ASP.DB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INNOBRA_ASP.DB.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadEmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("ActividadMaquinariaId")
                        .HasColumnType("int");

                    b.Property<int>("ActividadMaterialId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoHorasHombre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoHorasMaquina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoTotalMateriales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("HorasHombre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasMaquina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FaseId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.ActividadEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<decimal>("HorasTrabajadas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("ActividadEmpleados");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.ActividadMaquinaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasUtilizadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaquinariaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaquinariaId");

                    b.ToTable("ActividadMaquinarias");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.ActividadMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("ActividadMateriales");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.Fase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Fases");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.Maquinaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Maquinarias");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoUnidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.Actividad", b =>
                {
                    b.HasOne("INNOBRA_ASP.DB.Data.Entity.Fase", "Fase")
                        .WithMany("Actividades")
                        .HasForeignKey("FaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fase");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.ActividadEmpleado", b =>
                {
                    b.HasOne("INNOBRA_ASP.DB.Data.Entity.Empleado", "Empleado")
                        .WithMany("ActividadEmpleados")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.ActividadMaquinaria", b =>
                {
                    b.HasOne("INNOBRA_ASP.DB.Data.Entity.Maquinaria", "Maquinaria")
                        .WithMany("ActividadMaquinarias")
                        .HasForeignKey("MaquinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquinaria");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.ActividadMaterial", b =>
                {
                    b.HasOne("INNOBRA_ASP.DB.Data.Entity.Material", "Material")
                        .WithMany("ActividadMateriales")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.Fase", b =>
                {
                    b.HasOne("INNOBRA_ASP.DB.Data.Entity.Proyecto", "Proyecto")
                        .WithMany("Fases")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.Empleado", b =>
                {
                    b.Navigation("ActividadEmpleados");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.Fase", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.Maquinaria", b =>
                {
                    b.Navigation("ActividadMaquinarias");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.Material", b =>
                {
                    b.Navigation("ActividadMateriales");
                });

            modelBuilder.Entity("INNOBRA_ASP.DB.Data.Entity.Proyecto", b =>
                {
                    b.Navigation("Fases");
                });
#pragma warning restore 612, 618
        }
    }
}
